import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import { createRequire } from "module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/`;

const prod = process.argv[2] === "production";
const require = createRequire(import.meta.url);

// lineupjs ships ES modules with circular re-exports that esbuild can't
// statically resolve; use the prebuilt UMD bundle instead.
const lineupUMD = {
  name: "lineup-umd",
  setup(build) {
    build.onResolve({ filter: /^lineupjs$/ }, () => ({
      path: require.resolve("lineupjs/build/LineUpJS.js"),
    }));
  },
};

const copyCss = {
  name: "copy-css",
  setup(build) {
    // Obsidian + Hot-Reload expect `styles.css` next to main.js, but esbuild
    // emits `main.css`. Copy on every rebuild so `npm run dev` (watch mode)
    // also delivers fresh styles — otherwise CSS fixes never reach Obsidian.
    build.onEnd(() => {
      if (fs.existsSync("main.css")) fs.copyFileSync("main.css", "styles.css");
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  minify: prod,
  treeShaking: true,
  outdir: ".",
  entryNames: "[name]",
  // Bundle lineupjs assets (incl. inline SVG/font data) so the plugin works offline.
  loader: {
    ".png": "dataurl",
    ".svg": "dataurl",
    ".woff": "dataurl",
    ".woff2": "dataurl",
    ".eot": "dataurl",
    ".ttf": "dataurl",
    ".css": "css",
  },
  plugins: [lineupUMD, copyCss],
});

if (prod) {
  await context.rebuild();
  // Obsidian + Hot-Reload expect `styles.css` next to main.js.
  if (fs.existsSync("main.css")) fs.copyFileSync("main.css", "styles.css");
  process.exit(0);
} else {
  await context.watch();
}
